apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dmaxim/ml-system.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true